hebi_base_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

hebi_base_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['front_left_wheel', 'rear_left_wheel']
  right_wheel: ['front_right_wheel', 'rear_right_wheel']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 0.1
  velocity_rolling_window_size: 2

  # Base frame_id
  base_frame_id: base_link

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false

  # HEBI hardware provides wheel velocities
  estimate_velocity_from_position: false

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation: 0.51     # m
  wheel_radius:     0.1016   # m

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 6.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 6.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 12.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 12.0   # rad/s^2