# Teleop configuration for Microsoft Xbox One controller with Wireless USB Dongle.
# Left thumb-stick up/down for velocity, left/right for twist
# A button for enable
# Left thumb-stick button for enable-turbo
#
#
# BUTTON         Value
#   LB             4
#   RB             5
#   LS             9
#   RS             10
#   A              0
#   B              1
#   X              2
#   Y              3
#   View           6
#   Menu           7
#
# AXIS           Value
# Left Horiz.      0
# Left Vert.       1
# Right Horiz.     3
# Right Vert.      4
# LT               2
# RT               5
# D-pad Horiz.     6
# D-pad Vert.      7

teleop_twist_joy:
  axis_linear: 1
  scale_linear: 0.5
  scale_linear_turbo: 1.0
  axis_angular: 0
  scale_angular: 2.0
  enable_button: 0
  enable_turbo_button: 9
joy_node:
  deadzone: 0.1
  autorepeat_rate: 20
  dev: /dev/input/js0